### ISSUE TITLE
油猴脚本开发指南篇幅分类

### ISSUE THREAD

**Issue by CodFrm** [scriptscat/tampermonkey-learn-guide#2]
> 迁移一下之前的issue

油猴脚本开发指南教程目录
https://bbs.tampermonkey.net.cn/thread-184-1-1.html
(出处: 油猴中文网)

大类建议分为：
- 入门篇
  - 以学习后能够写一些简单的脚本为和使用常用GM API为标准
- 进阶篇
  - 以学习后能够写一些较为复杂的脚本为标准（简单Hook）
- 高级篇
  - 以一些高级用法为标准（Proxy、MutationObserver、）
- 刨析篇
- 工程化
- 实例篇
- 常见问题

**Comment by lihengdao666** [comment]
整理结束
