### ISSUE TITLE
一些文章需要更新吗

### ISSUE THREAD

**Issue by threeTrave** [scriptscat/tampermonkey-learn-guide#8]
我比较熟悉前端，最近了解到这个教程，这个教程质量很好，我很快的入门了。在编写示例里，比如b站小尾巴等，目前b站已经使用fetch而不是XMLHttpRequest发送请求，我能为它编写新的文章吗？这只是一个小的地方，确切的说我想知道如何为项目编写或修订文章呢？

**Comment by lihengdao666** [comment]
这个我也比较头疼，因为很多例子网站会随着时间流逝出现更新和修改的情况，比如b站的文章是想解释XHR的劫持修改以及CORS之类的相关知识，即使改成Fetch也很难随着维护过去，毕竟当初也为了Fetch的修改等搞了其他文章，目前没有想到太良好的解决办法...

**Comment by threeTrave** [comment]
好的，了解了
&nbsp;


君的名字是
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月8日(星期一) 中午11:47
收件人: ***@***.***&gt;; 
抄送: "张方耀 a bing ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [scriptscat/tampermonkey-learn-guide] 一些文章需要更新吗 (Issue #8)














 
这个我也比较头疼，因为很多例子网站会随着时间流逝出现更新和修改的情况，比如b站的文章是想解释XHR的劫持修改以及CORS之类的相关知识，即使改成Fetch也很难随着维护过去，毕竟当初也为了Fetch的修改等搞了其他文章，目前没有想到太良好的解决办法...

**Comment by lihengdao666** [comment]
关于修订文章目前主要围绕在将旧文章做适当补充以及提升美观度周围做工作

比如taozhiyu曾经做了大部分的翻新工作https://bbs.tampermonkey.net.cn/thread-6194-1-1.html

文章的新部分攥写可以在确定指南没有覆盖到的话跟我沟通确定好命题直接按格式写好pr过来

当然如果日常笔记性质的可以丢在https://bbs.tampermonkey.net.cn/     ，最后会采集一部分编写精良的合并过来

**Comment by lihengdao666** [comment]
> 关于修订文章目前主要围绕在将旧文章做适当补充以及提升美观度周围做工作
> 
> 比如taozhiyu曾经做了大部分的翻新工作https://bbs.tampermonkey.net.cn/thread-6194-1-1.html
> 
> 文章的新部分攥写可以在确定指南没有覆盖到的话跟我沟通确定好命题直接按格式写好pr过来
> 
> 当然如果日常笔记性质的可以丢在[https://bbs.tampermonkey.net.cn/，最后会采集一部分编写精良的合并过来]
